# pmg_routing:
#    resource: "@PmgSocialBundle/Resources/config/routing.yml"
#    prefix:   /pmg/

# nviba_deployment:
#    resource: "@NvibaDeploymentBundle/Resources/config/routing.yml"
#    prefix:   /

