nviba_sulu_overrides:
    resource: "@NvibaSuluOverridesBundle/Resources/config/routing.yml"
    prefix:   /

pmg_social:
    resource: "@PmgSocialBundle/Resources/config/routing.yml"
    prefix:   /social/

# nviba_deployment:
#    resource: "@NvibaDeploymentBundle/Resources/config/routing.yml"
#    prefix:   /

