parameters:
    nviba_sulu_overrides.event_listener.set_theme.class: Nviba\Bundle\SuluOverridesBundle\EventListener\SetThemeEventListener
    sulu_location.content.type.location.class: Nviba\Bundle\SuluOverridesBundle\Content\Types\LocationContentType
services:
    nviba_sulu_overrides.event_listener.set_theme:
        class: "%nviba_sulu_overrides.event_listener.set_theme.class%"
        public: true
        arguments:
            - "@sulu_core.webspace.request_analyzer"
            - "@liip_theme.active_theme"
            - "%nviba_sulu_overrides.portal_themes%"
        tags:
            - { name: kernel.event_listener, event: "%sulu_website.engine.initialize%", method: setActiveTheme }
            - { name: sulu.context, context: website }
